spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym?useSSL=false
    username: root
    password: Artur9211
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
data:
  path:
    trainee: classpath:data/Trainee.json
    trainer: classpath:data/Trainer.json
    training: classpath:data/Training.json
    trainingType: classpath:data/Training-type.json
    user: classpath:data/User.json

